# Generated by Django 2.0.5 on 2018-06-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_number', models.CharField(max_length=3)),
                ('camera_name', models.CharField(max_length=255)),
                ('camera_address', models.CharField(max_length=15)),
                ('avg_bitrate', models.CharField(max_length=20)),
                ('rec_enabled', models.BooleanField(default=False)),
                ('delete_type', models.CharField(max_length=4)),
                ('assigned_space', models.CharField(max_length=15)),
                ('rec_days', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('total_space', models.CharField(max_length=20)),
                ('camera_count', models.CharField(max_length=3)),
                ('server_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Server'),
        ),
    ]
