# Generated by Django 2.0.5 on 2018-06-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='camera_count',
        ),
    ]
