# Generated by Django 2.0.5 on 2018-06-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20180608_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='total_space',
            field=models.PositiveIntegerField(),
        ),
    ]
