# Generated by Django 2.0.5 on 2018-06-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20180608_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='avg_bitrate',
            field=models.CharField(choices=[('1MP', '1024'), ('2MP', '2048'), ('3MP', '3072'), ('4MP', '4096'), ('5MP', '5120'), ('6MP', '6144'), ('7MP', '7168'), ('8MP', '9192')], max_length=4),
        ),
    ]
