# Generated by Django 2.0.5 on 2018-06-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20180617_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='camera_name',
            new_name='camera_model',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='camera_number',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='rec_days',
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='assigned_space',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='camera',
            name='avg_bitrate',
            field=models.IntegerField(choices=[(1024, '1MP'), (2048, '2MP'), (3072, '3MP'), (4096, '4MP'), (5120, '5MP'), (6144, '6MP'), (7168, '7MP'), (9192, '8MP')]),
        ),
    ]
